#!/usr/bin/env node
"use strict";
/**
 * cli/checklist.js — writes VALIDATION.md, the one-page checklist that lets
 * a short call with a fluent Vietnamese speaker close the validation
 * requirement. Everything in it comes from the data tables (unverified.js)
 * or from the live scorer; nothing is hand-written, so it cannot drift.
 *
 *   node cli/checklist.js > VALIDATION.md
 *
 * test/unverified.test.js fails when the committed file is stale.
 */
const { collectUnverified } = require("../unverified.js");
const { FixtureScriptureProvider } = require("../providers/scripture.js");
const { StubModelProvider } = require("../providers/model.js");
const { loadMelodies, noteName } = require("../melodies.js");
const { forLanguage } = require("../tone/index.js");
const { search } = require("../search.js");

const dir = (d) => (d === "up" ? "UP" : d === "down" ? "DOWN" : "level");
const level = (n) => (n >= 4 ? "high" : n === 3 ? "mid" : "low");

/** Flagged and passing transition pairs from the baseline of a passage, in speaker terms. */
function pairsFrom(setting, wantFlagged, max) {
  const out = [];
  for (const c of setting.chunks) {
    for (let i = 1; i < c.rows.length && out.length < max; i++) {
      const r = c.rows[i];
      const prev = c.rows[i - 1];
      if (!r.constrained || r.contrary !== wantFlagged) continue;
      const from = prev.notes[prev.notes.length - 1];
      const to = r.notes[0];
      out.push(
        `"${prev.text} ${r.text}": the voice goes ${dir(r.speechDir)} into "${r.text}" ` +
          `(${prev.label} ends ${level(prev.shape[1])}, ${r.label} starts ${level(r.shape[0])}); ` +
          `the tune goes ${dir(r.melody)} (${noteName(from)} to ${noteName(to)})` +
          (wantFlagged ? ` — FLAGGED, severity ${r.severity}` : " — the tool says this one is fine")
      );
    }
  }
  return out;
}

async function main() {
  const scripture = new FixtureScriptureProvider();
  const melodies = loadMelodies();
  const vi = forLanguage("vi");
  const model = new StubModelProvider();
  const entries = collectUnverified();
  const speaker = entries.filter((e) => e.owner === "speaker");
  const musician = entries.filter((e) => e.owner !== "speaker");

  // Live cases, never hardcoded.
  const ps = await search({ passage: await scripture.getPassage("VI1925", "PSA.23.1-2"), melodies, toneModule: vi, baselineMelodyId: "new-britain", model });
  const flagged = pairsFrom(ps.baseline, true, 3);
  const control = pairsFrom(ps.baseline, false, 1);
  const jn = await search({ passage: await scripture.getPassage("VI1925", "JHN.3.16"), melodies, toneModule: vi, baselineMelodyId: "new-britain", model });
  // Mid-clause breaks in the baseline and in the winning setting; they can differ.
  const midClause = [];
  for (const [label, setting] of [["baseline", jn.baseline], ["winning setting", jn.results[0]]]) {
    if (!setting || !setting.chunking || !setting.chunking.breaks) continue;
    const syl = setting.chunks.flatMap((c) => c.rows);
    for (const b of setting.chunking.breaks) {
      if (syl[b - 1].trailing) continue;
      const text = `"${syl.slice(Math.max(0, b - 2), b).map((r) => r.text).join(" ")} | ${syl.slice(b, b + 2).map((r) => r.text).join(" ")}"`;
      const seen = midClause.find((m) => m.text === text);
      if (seen) seen.where.push(label);
      else midClause.push({ text, where: [label] });
    }
  }

  const L = [];
  L.push("# Validation checklist");
  L.push("");
  L.push(`Generated by \`node cli/checklist.js\` from the data tables and the live scorer. Do not edit by hand. ${entries.length} values are unverified.`);
  L.push("");
  L.push("**How to use.** Part A is one call with a fluent Vietnamese speaker, highest impact first; nothing in it needs them to understand the tool. Write their answer under each item. Part B needs a score or a hymnal, not a speaker. After the call, change the file named in brackets, set its status to `verified`, and regenerate this page.");
  L.push("");
  L.push("## Part A — one call with a Vietnamese speaker");
  L.push("");
  L.push("### A1. The six tones — decides every verdict `[tone/vietnamese.js]`");
  L.push("");
  L.push("Ask them to say **ma, mà, má, mả, mã, mạ** slowly, then in a short phrase. For each, we only need where the voice **starts** and where it **ends**.");
  L.push("");
  let n = 0;
  for (const e of speaker.filter((e) => e.category === "tone")) {
    n++;
    L.push(`${n}. **${e.title}.** We assume: ${e.assumed || e.ask}${e.assumed ? `. Ask: *${e.ask}*` : ""}${e.context ? ` (${e.context})` : ""}`);
    L.push("   - Answer: ");
  }
  L.push("");
  L.push("### A2. Does the tool flag real problems? — Psalm 23:1-2 on Amazing Grace, one syllable per note");
  L.push("");
  L.push("Hum the two notes, then sing the two words on them. Ask: *Does the second word still sound like itself, or does it turn into another word or nothing?*");
  L.push("");
  flagged.forEach((f, i) => { L.push(`${n + i + 1}. ${f}`); L.push("   - Answer: "); });
  n += flagged.length;
  control.forEach((f) => { n++; L.push(`${n}. Control — ${f}`); L.push("   - Answer: "); });
  L.push("");
  L.push("### A3. Where a singer may breathe `[data/break-penalties.json]`");
  L.push("");
  const bp = speaker.find((e) => e.category === "break-penalty");
  if (midClause.length) {
    n++;
    L.push(`${n}. **Concrete case, John 3:16.** The tool splits the verse for singing and, having no better option with this tune, takes a breath where there is no punctuation. Read the verse aloud with a breath at each place below. Ask: *Does that pause sound wrong, odd, or fine? Which of these is worse?*`);
    for (const m of midClause) { L.push(`   - ${m.text} (${m.where.join(" and ")})`); L.push("     - Answer: "); }
  } else {
    n++;
    L.push(`${n}. **John 3:16.** The current chunker places no mid-clause break in this verse on Amazing Grace, so there is no concrete case to ask about; re-check when the melody library changes.`);
  }
  n++;
  L.push(`${n}. **The penalty ratios.** We assume: ${bp.assumed} Ask: *${bp.ask}*`);
  L.push("   - Answer: ");
  L.push("");
  L.push("### A4. Do they know these tunes? `[data/melodies/*.json]`");
  L.push("");
  for (const e of speaker.filter((e) => e.category === "melody")) {
    n++;
    L.push(`${n}. **${e.title}** We assume: ${e.assumed}. Ask: *${e.ask}*`);
    L.push("   - Answer: ");
  }
  L.push("");
  L.push("## Part B — for a musician or a hymnal (no speaker needed)");
  L.push("");
  L.push("### B1. Melody note lists, least confident first");
  L.push("");
  const order = ["stille-nacht", "new-britain", "ode-to-joy", "ah-vous-dirai-je"];
  const notes = musician.filter((e) => e.category === "melody").sort((a, b) => order.indexOf(a.id.split(".")[1]) - order.indexOf(b.id.split(".")[1]));
  for (const e of notes) {
    n++;
    L.push(`${n}. **${e.title}** \`[${e.file}]\``);
    L.push(`   ${e.ask}`);
    L.push("");
    L.push("   ```");
    for (const line of e.assumed.split("\n")) L.push(`   ${line}`);
    L.push("   ```");
    L.push("   - Corrections: ");
  }
  L.push("");
  L.push("### B2. Thresholds `[data/scoring-thresholds.json]`");
  L.push("");
  const th = musician.find((e) => e.category === "threshold");
  n++;
  L.push(`${n}. **${th.title}.** We assume: ${th.assumed} Ask: *${th.ask}* (${th.context})`);
  L.push("   - Answer: ");
  L.push("");
  L.push("## After the call");
  L.push("");
  L.push("Change the value in the named file, set its `status` (or the melody's `verified`) accordingly, run `npm test`, and regenerate with `node cli/checklist.js > VALIDATION.md`. Until then, every report ends with the list of unverified values it depends on.");
  L.push("");
  return L.join("\n");
}

if (require.main === module) {
  main().then((text) => process.stdout.write(text)).catch((err) => { console.error(err); process.exit(1); });
}
module.exports = { main };
